### ISSUE TITLE
Remove the old index.html file

### ISSUE THREAD

**Issue by jesseajohnston** [madditay/test-site-1#2]
To get the site to publish the updated Jekyll version, you need to delete the old test html file that is curently `index.html` in the main repo directory. Then the whole site should publish using the Jekyll base theme, generated by the new index file, `index.markdown`.

**Comment by madditay** [comment]
I removed the old index file, but now nothing shows up at all on site. Is there something else I'm missing?

**Comment by madditay** [comment]
Wait, I pulled up the page and it's there and looks much better! The main page site just is blank. is that correct? 
First post: https://madditay.github.io/test-site-1/2024/09/22/MY-FIRST-POST.html
Main page: https://madditay.github.io/test-site-1/

**Comment by jesseajohnston** [comment]
There should be information about the site name and a basic menu of your post(s) on the main page. So if it's blank there's still something not quite working. You may need to push the repo again locally or make a change in the `_config.yml` file, commit locally, then push to the remote. I'll take another look as well. ...

**Comment by madditay** [comment]
Okay neat, the first page now shows up correctly, as does the post page, but there's no link to the post page from the main page. Is that correct?

**Comment by morskyjezek** [comment]
It's closer. Definitely. But still something is not working with the way that the theme is configured, so keep looking at that aspect. I'll also see what I can find out. The "minima" theme is a basic theme that can be imported to Jekyll and it should work as a "remote" theme (meaning that it is hosted somewhere on GitHub and then can be referenced by your site). In this case, the site doesn't seem to be pulling those files correctly. When I run it locally on my computer I see something like: 

```
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2024-09-26 19:59:51
                    index.markdown
      Remote Theme: "minima" is not a valid remote theme
       Jekyll Feed: Generating feed for posts
                    ...done in 0.6504 seconds.
```

But I know `minima` is a supported theme...

**Comment by morskyjezek** [comment]
See https://pages.github.com/themes/

**Comment by morskyjezek** [comment]
Try it with PR #4 - it's worth working on this more though to make it work with the merlot theme.

**Comment by morskyjezek** [comment]
Ok, I think I see what's going on. The `merlot` theme doesn't have layouts named `page` or `home` in its default form. You could add those, but when the index and new page are requesting them, it basically "breaks" the theme and instead of disaplaying, nothing except the markdown content displays. 

So, some things you can do: 

* change the layout line in the index file to: `layout: default`. 
* do the same thing on the new post
* change the theme reference in the `_config.yml` file theme back to `remote_theme: pages-themes/merlot@v0.2.0` 
* the menus still won't quite work but you can get the idea of how the display changes.

**Comment by morskyjezek** [comment]
If this all seemed a bit confusing, do try to stick with it. I'm going to discuss more of how jekyll works next week in class.

**Comment by madditay** [comment]
Sounds good! I'll probably wait to hear more about jekyll before tinkering more, but I definitely want to get a different theme to work just for the fun of it.

**Comment by morskyjezek** [comment]
You can probably close this issue, unless you are still working on it.
